# Generated by Django 2.2 on 2019-09-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_auto_20190914_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
